//
// Created by Backer on 2019/1/15.
//

#ifndef ANDROIDFABRICDEFECTDETECT_OPENCL_COMMON_H
#define ANDROIDFABRICDEFECTDETECT_OPENCL_COMMON_H
#include <opencl.h>
#endif //ANDROIDFABRICDEFECTDETECT_OPENCL_COMMON_H
